package main

import "github.com/charmbracelet/lipgloss"

// Style presets for TUI
var (
	StylePaddingApp     = lipgloss.NewStyle().Padding(1, 2)
	StylePaddingPanel   = lipgloss.NewStyle().Padding(1, 1)
	StylePaddingBtn     = lipgloss.NewStyle().Padding(0, 2)
	StylePaddingBtnWide = lipgloss.NewStyle().Padding(0, 3)
	StylePaddingLock    = lipgloss.NewStyle().Padding(0, 1)
	StyleHeading        = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorFgMain)).Background(lipgloss.Color(ColorBgMain)).Padding(0, 1)
	StyleSubHeading     = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorFgSub))
	StyleSectionTitle   = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorSection))
	StylePanel          = lipgloss.NewStyle().BorderStyle(lipgloss.RoundedBorder()).BorderForeground(lipgloss.Color(ColorBorderPanel)).Padding(1, 1)
	StyleLabel          = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorLabel)).Width(20)
	StyleHint           = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorHint))
	StyleColHeader      = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorColHeader))
	StyleOriginalValue  = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorOrigVal)).Width(10)
	StyleBounds         = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorBounds)).Width(14)
	StyleSafe           = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorSafe))
	StyleWarn           = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorWarn))
	StyleUnsafe         = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorUnsafe))
	StyleActiveTab      = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorTabActiveFg)).Background(lipgloss.Color(ColorTabActiveBg)).Padding(0, 2)
	StyleInactiveTab    = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorTabInactFg)).Background(lipgloss.Color(ColorTabInactBg)).Padding(0, 2)
	StyleRunBtn         = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorRunBtnFg)).Background(lipgloss.Color(ColorRunBtnBg)).Padding(0, 3)
	StyleRunningBtn     = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorRunBtnFg)).Background(lipgloss.Color(ColorRunningBg)).Padding(0, 3)
	StyleEffGood        = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorEffGood))
	StyleEffOk          = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorEffOk))
	StyleEffLow         = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorEffLow))
	StyleResultLabel    = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorResultLbl)).Width(24)
	StyleResultValue    = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorResultVal)).Width(14)
	StyleResultTheo     = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorResultTheo)).Width(14)
	StyleInfoLabel      = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorInfoLbl)).Width(28)
	StyleInfoValue      = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorInfoVal))
	StyleInfoPanel      = lipgloss.NewStyle().BorderStyle(lipgloss.RoundedBorder()).BorderForeground(lipgloss.Color(ColorInfoPanel)).Padding(1, 1)
	StyleStatus         = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorStatus))
	StyleBtn            = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorBtnFg)).Background(lipgloss.Color(ColorBtnBg)).Padding(0, 2)
	StyleBtnFocus       = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorBtnFocusFg)).Background(lipgloss.Color(ColorBtnFocusBg)).Padding(0, 2)
	StyleLockOn         = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorLockOnFg)).Background(lipgloss.Color(ColorLockOnBg)).Padding(0, 1)
	StyleLockOff        = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorLockOffFg)).Background(lipgloss.Color(ColorLockOffBg)).Padding(0, 1)
	StyleMetric         = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color(ColorMetric))
	StyleMetricMuted    = lipgloss.NewStyle().Foreground(lipgloss.Color(ColorMetricMute))
)
